import React, { useContext } from "react";
import Head from "next/head";
import Link from "next/link";
import { Store } from "../utils/Store";

export default function Layout({title,children }) {
  const {state,dispatch}=useContext(Store);
  const {cart}=state;
  return (
    <>
      <Head>
        <title>{title ? title + "-Amazona" : "Amazona"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-12 items-center px-4 justify-between shadow-md">
            <Link href="/" passHref legacyBehavior>
              <a className="text-lg font-bold">amazona</a>
            </Link>
            <div>
              <Link passHref legacyBehavior href="/cart"><a className="p-2">
                {cart.cartItems.length>0 && (
                  <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                    {cart.cartItems.reduce((a,c)=>a+c.quantity,0)}
                  </span>
                )}
                Cart
                </a></Link>
              <Link passHref legacyBehavior href="/login"><a className="p-2">Login</a></Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center shadow-inner items-center">Copyright @ 2022 Amazona</footer>
      </div>
    </>
  );
}
